### ISSUE TITLE
Missing Access issue

### ISSUE THREAD

**Issue by DJJones66** [drobbins329/Discord.Net-V3-Bot-Tutorial#1]
When I run this I get this error from Discord

Discord.Net.HttpException: The server responded with error 50001: Missing Access

Any idea why?

Thank you.

I did build the config as per your instructions.

**Comment by drobbins329** [comment]
Did you invite the bot with bot and applications.commands scopes?

**Comment by DJJones66** [comment]
Yes, here is the link I used

https://discord.com/api/oauth2/authorize?client_id=BotID&permissions=8&scope=bot%20applications.commands

Thanks for the speedy reply

**Comment by drobbins329** [comment]
You can send me a friend request on discord at KeylAmi#9305
Or, share some code here. (Be sure to remove your bot token from shared code)

**Comment by DJJones66** [comment]
I sent a friend request, I am using your code from github.  Only thing I added was the config.yml

Since I am using a bot id I made a month ago for learning, maybe I need to create a new one following your first ep and see if that makes a difference perhaps?  

I know google was no help on this matter..

**Comment by drobbins329** [comment]
Bot id? Or bot token?

**Comment by poopman97** [comment]
any solution?
